version: '3'

services:
  db:
    image: mysql:8.0.16
    container_name: play_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rp
      MYSQL_DATABASE: play_notes
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default-authentication-plugin=mysql_native_password
    ports:
      - 1234:3306
    hostname: db

  web:
    image: hseeberger/scala-sbt
    container_name: play_scala
    volumes:
      - ./notes:/app/notes
    tty: true
    ports:
      - 9000:9000
    links:
      - db
